=== mazetsveronika/xmlparsing/out/production/xmlparsing/resources/data/vouchers.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.dreamtravel.by/vouchers"
        xmlns:tns="http://www.dreamtravel.by/vouchers"
        elementFormDefault="qualified">
    <element name="vouchers">
        <complexType>
            <sequence>
                <element name="voucher" type="tns:voucher" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="voucher">
        <sequence>
            <element name="typeOfVoucher" type="tns:typeOfVoucher"/>
            <element name="country" type="string"/>
            <element name="city" type="string"/>
            <element name="numberDays" type="positiveInteger"/>
            <element name="numberNights" type="positiveInteger"/>
            <element name="transport" type="string"/>
            <element name="hotelCharacteristic" type="tns:hotelCharacteristic"/>
           </sequence>
        <attribute name="id" type="tns:voucher" use="required" />
        <attribute name="voucher"  use="optional" default="false"/>
            </complexType>
    <simpleType name="id">
        <restriction base="ID">
            <pattern value="p\d{1,4}"/>
        </restriction>
    </simpleType>

    <simpleType name="typeOfVoucher">
            <restriction base="string">
                <enumeration value="Weekend pass"/>
                <enumeration value="Tour"/>
                <enumeration value="Holidays"/>
         </restriction>
        </simpleType>

      <simpleType name="country">
        <restriction base="string">
            <enumeration value="Russia"/>
            <enumeration value="Belarus"/>
            <enumeration value="Switzerland"/>
            <enumeration value="Egypt"/>
        </restriction>
    </simpleType>

    <simpleType name="city">
        <restriction base="string">
            <enumeration value="Moscow"/>
            <enumeration value="Saint-Petersburg"/>
            <enumeration value="Minsk-Belovezhskaya Pushcha-Minsk"/>
            <enumeration value="Zurich"/>
            <enumeration value="Sharm-El-Sheikh"/>
        </restriction>
    </simpleType>

    <simpleType name="numberDays">
        <restriction base="positiveInteger">
            <minInclusive value="1"/>
            <maxExclusive value="30"/>
        </restriction>
    </simpleType>

    <simpleType name="numberNights">
        <restriction base="positiveInteger">
            <minInclusive value="1"/>
            <maxExclusive value="30"/>
        </restriction>
    </simpleType>


    <complexType name="hotelCharacteristic">
           <sequence>
               <element name="hotelStars" type="positiveInteger"/>
               <element name="hotelFood" type="string"/>
               <element name="hotelRoom" type="string"/>
               <element name="tv" type="string"/>
               <element name="airConditioner" type="string"/>
           </sequence>
       </complexType>

    <simpleType name="hotelStars">
    <restriction base="positiveInteger">
        <minInclusive value="1"/>
        <maxExclusive value="5"/>
            </restriction>
        </simpleType>

    <simpleType name="hotelFood">
        <restriction base="string">
            <enumeration value="AO"/>
            <enumeration value="CB"/>
            <enumeration value="BB"/>
            <enumeration value="HB"/>
            <enumeration value="FB"/>
            <enumeration value="FB+"/>
            <enumeration value="AI"/>
        </restriction>
    </simpleType>

    <simpleType name="hotelRoom">
        <restriction base="string">
            <enumeration value="single"/>
            <enumeration value="double"/>
            <enumeration value="triple"/>
                  </restriction>

    </simpleType>
    <simpleType name="tv">
        <restriction base="string">
            <enumeration value="yes"/>
            <enumeration value="no"/>
            </restriction>

    </simpleType>
    <simpleType name="airConditioner">
        <restriction base="string">
            <enumeration value="yes"/>
            <enumeration value="no"/>
        </restriction>
    </simpleType>
</schema>

=== mazetsveronika/xmlparsing/resources/vouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<vouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.dreamtravel.by/vouchers"
        xsi:schemaLocation="http://www.dreamtravel.by/vouchers vouchers.xsd">

<voucher id="w01">
    <typeOfVoucher>Weekend pass</typeOfVoucher>
        <country>Russia</country>
        <city>Moscow</city>
        <departure>2022-03-09</departure>
        <numberDays>2</numberDays>
        <numberNights>1</numberNights>
        <transport>bus</transport>
        <hotelCharacteristic>
            <hotelStars>4</hotelStars>
            <hotelFood>NO</hotelFood>
            <hotelRoom>single</hotelRoom>
            <tv>yes</tv>
            <airConditioner>yes</airConditioner>
        </hotelCharacteristic>
</voucher>

<voucher id="w02" >
            <typeOfVoucher>Weekend pass</typeOfVoucher>
            <country>Russia</country>
            <city>Saint-Petersburg</city>
            <departure>2022-04-03</departure>
            <numberDays>3</numberDays>
            <numberNights>2</numberNights>
            <transport>bus</transport>
            <hotelCharacteristic>
                <hotelStars>5</hotelStars>
                <hotelFood>FB</hotelFood>
                <hotelRoom>double</hotelRoom>
                <tv>yes</tv>
                <airConditioner>yes</airConditioner>
            </hotelCharacteristic>
</voucher>

<voucher id="t03" >
        <typeOfVoucher>Tour</typeOfVoucher>
        <country>Belarus</country>
        <city>Minsk-Belovezhskaya Pushcha-Minsk</city>
        <departure>2022-04-28</departure>
        <numberDays>2</numberDays>
        <numberNights>1</numberNights>
        <transport>bus</transport>
        <hotelCharacteristic>
            <hotelStars>4</hotelStars>
            <hotelFood>BB</hotelFood>
            <hotelRoom>double</hotelRoom>
            <tv>yes</tv>
            <airConditioner>no</airConditioner>
        </hotelCharacteristic>
</voucher>

<voucher id="h04">
    <typeOfVoucher>Holidays</typeOfVoucher>
        <country>Switzerland</country>
        <city>Zurich</city>
        <departure>2022-04-17</departure>
        <numberDays>7</numberDays>
        <numberNights>6</numberNights>
        <transport>airplane</transport>
         <hotelCharacteristic>
            <hotelStars>5</hotelStars>
            <hotelFood>AI</hotelFood>
            <hotelRoom>double</hotelRoom>
            <tv>yes</tv>
            <airConditioner>yes</airConditioner>
        </hotelCharacteristic>
</voucher>

<voucher id="h05" >
    <typeOfVoucher>Holidays</typeOfVoucher>
        <country>Egypt</country>
        <city>Sharm-El-Sheikh</city>
        <departure>2022-04-25</departure>
        <numberDays>10</numberDays>
        <numberNights>9</numberNights>
        <transport>airplane</transport>
        <hotelCharacteristic>
            <hotelStars>5</hotelStars>
            <hotelFood>AI</hotelFood>
            <hotelRoom>triple</hotelRoom>
            <tv>yes</tv>
            <airConditioner>yes</airConditioner>
        </hotelCharacteristic>
    </voucher>
</vouchers>

=== mazetsveronika/xmlparsing/src/resources/data/vouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<vouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.dreamtravel.by/vouchers"
        xsi:schemaLocation="http://www.dreamtravel.by/vouchers vouchers.xsd">

<voucher id="01">
    <typeOfVoucher>Weekend pass</typeOfVoucher>
        <country>Russia</country>
        <city>Moscow</city>
        <numberDays>2</numberDays>
        <numberNights>1</numberNights>
        <transport>bus</transport>
        <hotelCharacteristic>
            <hotelStars>4</hotelStars>
            <hotelFood>NO</hotelFood>
            <hotelRoom>single</hotelRoom>
            <tv>yes</tv>
            <airConditioner>yes</airConditioner>
        </hotelCharacteristic>
</voucher>

<voucher id="02" >
            <typeOfVoucher>Weekend pass</typeOfVoucher>
            <country>Russia</country>
            <city>Saint-Petersburg</city>
            <numberDays>3</numberDays>
            <numberNights>2</numberNights>
            <transport>bus</transport>
            <hotelCharacteristic>
                <hotelStars>5</hotelStars>
                <hotelFood>FB</hotelFood>
                <hotelRoom>double</hotelRoom>
                <tv>yes</tv>
                <airConditioner>no</airConditioner>
            </hotelCharacteristic>
</voucher>

<voucher id="03" >
        <typeOfVoucher>Tour</typeOfVoucher>
        <country>Belarus</country>
        <city>Minsk-Belovezhskaya Pushcha-Minsk</city>
        <numberDays>2</numberDays>
        <numberNights>1</numberNights>
        <transport>bus</transport>
        <hotelCharacteristic>
            <hotelStars>4</hotelStars>
            <hotelFood>BB</hotelFood>
            <hotelRoom>double</hotelRoom>
            <tv>yes</tv>
            <airConditioner>no</airConditioner>
        </hotelCharacteristic>
</voucher>

<voucher id="04">
    <typeOfVoucher>Holidays</typeOfVoucher>
        <country>Switzerland</country>
        <city>Zurich</city>
        <numberDays>7</numberDays>
        <numberNights>6</numberNights>
        <transport>airplane</transport>
        <hotelCharacteristic>
            <hotelStars>5</hotelStars>
            <hotelFood>AI</hotelFood>
            <hotelRoom>double</hotelRoom>
            <tv>yes</tv>
            <airConditioner>yes</airConditioner>
        </hotelCharacteristic>
</voucher>

<voucher id="05" >
    <typeOfVoucher>Holidays</typeOfVoucher>
        <country>Egypt</country>
        <city>Sharm-El-Sheikh</city>
        <numberDays>10</numberDays>
        <numberNights>9</numberNights>
        <transport>airplane</transport>
        <hotelCharacteristic>
            <hotelStars>5</hotelStars>
            <hotelFood>AI</hotelFood>
            <hotelRoom>triple</hotelRoom>
            <tv>yes</tv>
            <airConditioner>yes</airConditioner>
        </hotelCharacteristic>
    </voucher>
</vouchers>
